### ISSUE TITLE
Cambiar link en la página del repositorio

### ISSUE THREAD

**Issue by agbeltran** [carpentries/shell-novice-es-archive#12]
Aunque este sea un repositorio temporal, sería útil cambiar el link en la [página del repositorio](https://github.com/Carpentries-ES/shell-novice) de:

http://swcarpentry.github.io/shell-novice/

a
https://carpentries-es.github.io/shell-novice/

**Comment by orchid00** [comment]
vamos a subir la leccion cuando esté revisada por completo, será pronto https://github.com/Carpentries-ES/shell-novice/projects/1 y @map0logo luego se va contactar con la gente de Carpentries especialmente con Erin para mover la leccion revisada. Solo falta mi OK.

**Comment by agbeltran** [comment]
Sí, gracias por la información sobre el lugar definitivo de la lección. 
Igual creo que es útil poner el enlace a donde la lección se puede ver traducida, desde la página del repositorio (va adjunta la imagen del enlace al que me refiero). 
![screen shot 2017-10-31 at 12 11 12](https://user-images.githubusercontent.com/1417033/32223325-cd246360-be34-11e7-8fce-ca5d65870788.png)

**Comment by agbeltran** [comment]
Yo no tengo permiso para cambiar el enlace.

**Comment by orchid00** [comment]
@agbeltran hice el cambio que sugeriste, pero no se ve la leccion traducida por que los md files estan en "_episodes_es" en vez de "_episodes" 
Talvez @map0logo sabe donde esta el link a ese folder.

**Comment by agbeltran** [comment]
OK, gracias! Para las lecciones en español, no deberíamos mantener las traducciones en _episodes así no tenemos que cambiar la estructura de los proyectos? Si queremos ver los episodios en inglés originales, siempre podemos ir al repositorio original. De esta forma, también podremos visualizar los episodios en español fácilmente (sin cambiar la estructura). Gracias

**Comment by orchid00** [comment]
Nuevamente, @map0logo es el que sabe de eso. él creó el folder _episodes_es.

Francisco, me gustaría que por favor me ayudes en esta clarificación, por que si debemos mover todo luego a `episodes` va ser mas complicado y quiero saber antes de asignar las traducciones de R.

**Comment by orchid00** [comment]
Will close this, because it is also some unresolvable issue at the moment
