### ISSUE TITLE
move extra episodes to discussion

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/shell-novice-es-archive#15]
Episodes 08, 09, and 10 look very useful, but are not part of the existing lesson set. In order to ensure that the initial publication of these lessons are in synch with the existing lessons, please move these episodes to _extras/discussion.md.

**Comment by ErinBecker** [comment]
I've done this in my fork: https://github.com/ErinBecker/shell-novice-es

The commit is: https://github.com/ErinBecker/shell-novice-es/commit/55c33f45bc706d5aecca8245dbd122dbf999125e

**Comment by orchid00** [comment]
I am OK with moving this to _extras I just haven't got the time to do it?
May I ask @Helysalgado @olemis ? could you please move this files?
