### ISSUE TITLE
translate non-episode files

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/shell-novice-es-archive#16]
The following files need translations before publication:

- [x] [setup.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/setup.md)
- [x] [index.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/index.md)

The following files can be translated later (after publication): 

- [x] [reference.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/reference.md)
- [x] [README.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/README.md)
- [x] [_extras/discuss.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/_extras/discuss.md)
- [x] [_extras/guide.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/_extras/guide.md)

The following files need translations, but I think these files come in from styles: 
- [x] [LICENSE.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/LICENSE.md)
- [x] [CONTRIBUTING.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/CONTRIBUTING.md)
- [x] [CONDUCT.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/CONDUCT.md)

**Comment by orchid00** [comment]
@ErinBecker Translation of the two files needed before publication:

https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/_episodes_es/setup.md
https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/_episodes_es/index.md

**Comment by ErinBecker** [comment]
I'm working on translating the styles repo so that we only need to do the
formatting files once. Will update this issue on Monday with progress.

**Comment by ErinBecker** [comment]
I've translated the styles repo: https://github.com/erinbecker/styles-es

Next, I need to pull in those changes into the individual lesson repos (shell-novice and git-novice) so that the changes propagate. @rgaiacs is helping me with this. 

If anyone sees problems with the translations in https://github.com/erinbecker/styles-es it would be greatly appreciated to put in a PR to my fork. I'm waiting to submit a PR to this repo until after I've gotten the styles merged.

**Comment by ErinBecker** [comment]
Thanks @orchid00 for those translated files. I don't know how I missed them before. I've updated by repo with those files. https://github.com/ErinBecker/shell-novice-es/commit/d66402b53e13e47b2d4f7d1c64ec915f20b8bded

**Comment by orchid00** [comment]
@ErinBecker would you like to open a new issue with the files that need to be translated later? so we can close this issue with the 2 files setup and index?

**Comment by rgaiacs** [comment]
@ErinBecker Can you enable issues at https://github.com/ErinBecker/shell-novice-es? You need to change https://github.com/ErinBecker/shell-novice-es/blob/gh-pages/_config.yml#L59 to

~~~
      type: episodes
~~~

otherwise the episodes will not be listed in `index.html`. I think this was the problem that you have yesterday.

**Comment by rgaiacs** [comment]
You also need to change https://github.com/ErinBecker/shell-novice-es/blob/gh-pages/_config.yml#L47 to

~~~
  episodes:
~~~
