### ISSUE TITLE
The terminal

### ISSUE THREAD

**Issue by orchid00** [carpentries/shell-novice-es-archive#19]
I had initiated a poll to decide whether to keep the terminal as "El terminal" or to change as ""La terminal".
We had discussed this already, but now, we need to re-start this discussion with some backup data.
The poll will close feb 22nd. The answer with most votes will be taken
Please contribute with your vote 
https://goo.gl/forms/M3qiYKkRYwupjlfK2

**Comment by raynamharris** [comment]
Here's a tweet to share to get more people voting!
https://twitter.com/orchid00/status/965681285380354048

**Comment by raynamharris** [comment]
@orchid00 How many votes so far?

**Comment by agbeltran** [comment]
Voté y compartí el tweet, pero además la Real Academia Española dice que es femenina: http://dle.rae.es/?id=ZYm7znz

**Comment by dledezma** [comment]
Yo voté femenino, pero respecto a la RAE (http://dle.rae.es/?id=ZYm7znz), en la acepción que más se acerca al uso que le estamos dando dice “masculino o femenino” (m. o f.). 

5. m. o f. Inform. Máquina con teclado y pantalla mediante la cual se proporcionan datos a una computadora central o se obtiene información de ella.

Entiendo que por eso es importante la encuesta.

**Comment by orchid00** [comment]
Hola, vamos 94 votos y la mayoria dice "la" terminal.
Voy a compartir los resultados de la encuesta el 22 de Feb al final de mi dia en este issue.
Hay varias personas que comentaron que la linea de comandos es otra opcion, pero considero que cambiar el terminal por la terminal es lo optimo.

**Comment by orchid00** [comment]
Hola, vamos 94 votos y la mayoria dice "la" terminal.
Voy a compartir los resultados de la encuesta el 22 de Feb al final de mi dia en este issue.
Hay varias personas que comentaron que la linea de comandos es otra opcion, pero considero que cambiar el terminal por la terminal es lo optimo.

**Comment by orchid00** [comment]
So a pedido de Erin,
We are archiving this repo to work on the published repo https://swcarpentry.github.io/shell-novice-es/

voy a compartir los resultados de la encuesta en el nuevo repo
